baseURL = ""
languageCode = "en-us"
title = "lalaours's Journey"
disableKinds = ["sitemap", "RSS"]
theme = "hugo-webslides"
themesdir = "themes"
tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  author = "Lalaours"
  homepage = "https://lalaours.github.io/"


[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[blackfriday]
extensionsmask = ["autoHeaderIds"]
